/* tslint:disable */
/* eslint-disable */
/**
 * Remote Examination Api
 * Remote Examination Support management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: davidtruhlarac@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsultationEntry
 */
export interface ConsultationEntry {
    /**
     * Unique id of the consultation entry
     * @type {string}
     * @memberof ConsultationEntry
     */
    id: string;
    /**
     * Unique identifier of the patient
     * @type {string}
     * @memberof ConsultationEntry
     */
    patientId: string;
    /**
     * Full name of the patient
     * @type {string}
     * @memberof ConsultationEntry
     */
    patientName: string;
    /**
     * Primary condition or reason for consultation
     * @type {string}
     * @memberof ConsultationEntry
     */
    condition?: string;
    /**
     * Current status of the consultation
     * @type {string}
     * @memberof ConsultationEntry
     */
    status: ConsultationEntryStatusEnum;
    /**
     * Timestamp when the consultation was created
     * @type {Date}
     * @memberof ConsultationEntry
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ConsultationEntryStatusEnum = {
    Active: 'active',
    Pending: 'pending',
    Closed: 'closed'
} as const;
export type ConsultationEntryStatusEnum = typeof ConsultationEntryStatusEnum[keyof typeof ConsultationEntryStatusEnum];


/**
 * Check if a given object implements the ConsultationEntry interface.
 */
export function instanceOfConsultationEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ConsultationEntryFromJSON(json: any): ConsultationEntry {
    return ConsultationEntryFromJSONTyped(json, false);
}

export function ConsultationEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsultationEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patientId'],
        'patientName': json['patientName'],
        'condition': !exists(json, 'condition') ? undefined : json['condition'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ConsultationEntryToJSON(value?: ConsultationEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patientId': value.patientId,
        'patientName': value.patientName,
        'condition': value.condition,
        'status': value.status,
        'createdAt': (value.createdAt.toISOString()),
    };
}

