/* tslint:disable */
/* eslint-disable */
/**
 * Remote Examination Api
 * Remote Examination Support management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: davidtruhlarac@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommunicationProtocol,
  ConsultationEntry,
} from '../models';
import {
    CommunicationProtocolFromJSON,
    CommunicationProtocolToJSON,
    ConsultationEntryFromJSON,
    ConsultationEntryToJSON,
} from '../models';

export interface DeleteConsultationEntryRequest {
    ambulanceId: string;
    entryId: string;
}

export interface GetConsultationEntriesRequest {
    ambulanceId: string;
}

export interface GetConsultationEntryRequest {
    ambulanceId: string;
    entryId: string;
}

export interface GetConsultationProtocolRequest {
    ambulanceId: string;
    entryId: string;
}

export interface UpdateConsultationEntryRequest {
    ambulanceId: string;
    entryId: string;
    consultationEntry: ConsultationEntry;
}

export interface UpdateConsultationProtocolRequest {
    ambulanceId: string;
    entryId: string;
    communicationProtocol: CommunicationProtocol;
}

/**
 * AmbulanceRemoteConsultationApi - interface
 * 
 * @export
 * @interface AmbulanceRemoteConsultationApiInterface
 */
export interface AmbulanceRemoteConsultationApiInterface {
    /**
     * 
     * @summary Deletes a consultation entry
     * @param {string} ambulanceId 
     * @param {string} entryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceRemoteConsultationApiInterface
     */
    deleteConsultationEntryRaw(requestParameters: DeleteConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a consultation entry
     */
    deleteConsultationEntry(requestParameters: DeleteConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using ambulanceId you get list of active remote consultation entries
     * @summary Provides list of active remote consultation cases
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceRemoteConsultationApiInterface
     */
    getConsultationEntriesRaw(requestParameters: GetConsultationEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ConsultationEntry>>>;

    /**
     * By using ambulanceId you get list of active remote consultation entries
     * Provides list of active remote consultation cases
     */
    getConsultationEntries(requestParameters: GetConsultationEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConsultationEntry>>;

    /**
     * 
     * @summary Provides a single consultation entry
     * @param {string} ambulanceId 
     * @param {string} entryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceRemoteConsultationApiInterface
     */
    getConsultationEntryRaw(requestParameters: GetConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsultationEntry>>;

    /**
     * Provides a single consultation entry
     */
    getConsultationEntry(requestParameters: GetConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsultationEntry>;

    /**
     * 
     * @summary Provides the communication protocol for a consultation
     * @param {string} ambulanceId 
     * @param {string} entryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceRemoteConsultationApiInterface
     */
    getConsultationProtocolRaw(requestParameters: GetConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunicationProtocol>>;

    /**
     * Provides the communication protocol for a consultation
     */
    getConsultationProtocol(requestParameters: GetConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunicationProtocol>;

    /**
     * 
     * @summary Updates a consultation entry
     * @param {string} ambulanceId 
     * @param {string} entryId 
     * @param {ConsultationEntry} consultationEntry Consultation entry to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceRemoteConsultationApiInterface
     */
    updateConsultationEntryRaw(requestParameters: UpdateConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsultationEntry>>;

    /**
     * Updates a consultation entry
     */
    updateConsultationEntry(requestParameters: UpdateConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsultationEntry>;

    /**
     * 
     * @summary Updates the communication protocol
     * @param {string} ambulanceId 
     * @param {string} entryId 
     * @param {CommunicationProtocol} communicationProtocol 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceRemoteConsultationApiInterface
     */
    updateConsultationProtocolRaw(requestParameters: UpdateConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunicationProtocol>>;

    /**
     * Updates the communication protocol
     */
    updateConsultationProtocol(requestParameters: UpdateConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunicationProtocol>;

}

/**
 * 
 */
export class AmbulanceRemoteConsultationApi extends runtime.BaseAPI implements AmbulanceRemoteConsultationApiInterface {

    /**
     * Deletes a consultation entry
     */
    async deleteConsultationEntryRaw(requestParameters: DeleteConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling deleteConsultationEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling deleteConsultationEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/remote-consultation/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a consultation entry
     */
    async deleteConsultationEntry(requestParameters: DeleteConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConsultationEntryRaw(requestParameters, initOverrides);
    }

    /**
     * By using ambulanceId you get list of active remote consultation entries
     * Provides list of active remote consultation cases
     */
    async getConsultationEntriesRaw(requestParameters: GetConsultationEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ConsultationEntry>>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getConsultationEntries.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/remote-consultation/{ambulanceId}/entries`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConsultationEntryFromJSON));
    }

    /**
     * By using ambulanceId you get list of active remote consultation entries
     * Provides list of active remote consultation cases
     */
    async getConsultationEntries(requestParameters: GetConsultationEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConsultationEntry>> {
        const response = await this.getConsultationEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Provides a single consultation entry
     */
    async getConsultationEntryRaw(requestParameters: GetConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsultationEntry>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getConsultationEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling getConsultationEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/remote-consultation/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsultationEntryFromJSON(jsonValue));
    }

    /**
     * Provides a single consultation entry
     */
    async getConsultationEntry(requestParameters: GetConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsultationEntry> {
        const response = await this.getConsultationEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Provides the communication protocol for a consultation
     */
    async getConsultationProtocolRaw(requestParameters: GetConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunicationProtocol>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getConsultationProtocol.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling getConsultationProtocol.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/remote-consultation/{ambulanceId}/entries/{entryId}/protocol`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunicationProtocolFromJSON(jsonValue));
    }

    /**
     * Provides the communication protocol for a consultation
     */
    async getConsultationProtocol(requestParameters: GetConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunicationProtocol> {
        const response = await this.getConsultationProtocolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a consultation entry
     */
    async updateConsultationEntryRaw(requestParameters: UpdateConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsultationEntry>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling updateConsultationEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling updateConsultationEntry.');
        }

        if (requestParameters.consultationEntry === null || requestParameters.consultationEntry === undefined) {
            throw new runtime.RequiredError('consultationEntry','Required parameter requestParameters.consultationEntry was null or undefined when calling updateConsultationEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/remote-consultation/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConsultationEntryToJSON(requestParameters.consultationEntry),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsultationEntryFromJSON(jsonValue));
    }

    /**
     * Updates a consultation entry
     */
    async updateConsultationEntry(requestParameters: UpdateConsultationEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsultationEntry> {
        const response = await this.updateConsultationEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the communication protocol
     */
    async updateConsultationProtocolRaw(requestParameters: UpdateConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommunicationProtocol>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling updateConsultationProtocol.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling updateConsultationProtocol.');
        }

        if (requestParameters.communicationProtocol === null || requestParameters.communicationProtocol === undefined) {
            throw new runtime.RequiredError('communicationProtocol','Required parameter requestParameters.communicationProtocol was null or undefined when calling updateConsultationProtocol.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/remote-consultation/{ambulanceId}/entries/{entryId}/protocol`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CommunicationProtocolToJSON(requestParameters.communicationProtocol),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommunicationProtocolFromJSON(jsonValue));
    }

    /**
     * Updates the communication protocol
     */
    async updateConsultationProtocol(requestParameters: UpdateConsultationProtocolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommunicationProtocol> {
        const response = await this.updateConsultationProtocolRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
